### PR TITLE
Jlam/reading config file

### PR DESCRIPTION
**Pull request by Jacky-Lam-CY**
Added a Common static library for functions that will be used by both client and server projects.
Added read and write file function in Common.
Added MS Test project setup and tests for read/write files.

### CODE REVIEW

**Comment by Dom17Pham** [comment]
Looks fine to me, should be good for merge.

**Review by Dom17Pham — APPROVED** [review]
Looks fine to me, should be good to merge.

**Comment by Amanuel-Negussie** [comment]
LGTM!

**Review by Amanuel-Negussie — COMMENTED** [review]
LGTM!

**Pull request merged**
